[debian_minimal]
git-tree-sha1 = "a5daaaecd41469f8db6315966fbb3d5abced9125"

    [[debian_minimal.download]]
    sha256 = "88beb5b70b4a6c5b28dd48c8be2cbf456dbebad7af8ed9830f03bce3fc88d26a"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v5.50/debian_minimal.x86_64.tar.gz"

[package_linux]
git-tree-sha1 = "3e69bfa92895472318457b4bbe7fa349244c41a0"
lazy = true

    [[package_linux.download]]
    sha256 = "5b26a76edd76a1bd929495f419db051eb1c69dce1426efe69e9b7459ec4dfef6"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v5.50/package_linux.x86_64.tar.gz"
